site_name: Algoraid
docs_dir: documentation
repo_url: https://github.com/algoraid/docs

theme:
  name: material
  features:
    - navigation.sections
    - navigation.path
    - navigation.indexes
    - navigation.footer

plugins:
  - table-reader
  - search
  - autolinks
  - drawio_file
  - mermaid2:
      version: 9.3.0

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - attr_list
  - md_in_html
  - pymdownx.tabbed:
      alternate_style: true 